ドメイン利用ガイドラインの追加
until-tsukuba/www.tsukuba.dev pull request #2
Opened 2024-01-30 12:38 UTC by oageo

https://www.tsukuba.dev に存在するドメイン利用ガイドラインの草案を追加しました。適宜添削していただければと存じます。

2024-01-30 18:45 UTC, eniehack commented
申請フローが示されていないため、追記する必要がある

2024-01-31 08:52 UTC, eniehack commented on src/pages/guidelines/index.astro
> +			<p>利用開始した後に、UNTIL.・全代会情報処理推進特別委員会が不適当と認める内容となった場合、貸し出し対象に連絡を取った後適切な応答が無い場合、サブドメインの貸し出しを中止する。</p>
これ、ulタグを使わない理由って何？

2024-01-31 09:05 UTC, oageo commented on src/pages/guidelines/index.astro
> +			<p>利用開始した後に、UNTIL.・全代会情報処理推進特別委員会が不適当と認める内容となった場合、貸し出し対象に連絡を取った後適切な応答が無い場合、サブドメインの貸し出しを中止する。</p>
最初は文章にしようと思っていたのですが、思ったより箇条書きになってしまった跡地ですね。

2024-03-03 09:10 UTC, eniehack requested changes

2024-03-03 09:10 UTC, eniehack commented on src/pages/guidelines/index.astro
> +						利用開始した後に、UNTIL.・全代会情報処理推進特別委員会が不適当と認める内容となった場合、貸し出し対象に連絡を取った後適切な応答が無い場合、サブドメインの貸し出しを中止する。
やっぱり「適切な応答」だけではわかりにくい（~~我々も利用者も神祇官ではないので~~）
ここは説明を加えるべきじゃない？

2024-03-03 09:10 UTC, eniehack commented on src/pages/guidelines/index.astro
> +						利用開始した後に、UNTIL.・全代会情報処理推進特別委員会が不適当と認める内容となった場合、貸し出し対象に連絡を取った後適切な応答が無い場合、サブドメインの貸し出しを中止する。
これはどーすか
```suggestion
						利用開始した後に、UNTIL.または全代会情報処理推進特別委員会が不適当と認める内容となった場合、貸し出し対象に連絡を取った後適切な応答が無いとき、利用者の同意を確認せずにサブドメインの貸し出しを中止する場合があること。
```

2024-03-03 09:10 UTC, oageo commented on src/pages/guidelines/index.astro
> +						利用開始した後に、UNTIL.・全代会情報処理推進特別委員会が不適当と認める内容となった場合、貸し出し対象に連絡を取った後適切な応答が無い場合、サブドメインの貸し出しを中止する。
正しそう

2024-03-03 09:11 UTC, oageo commented on src/pages/guidelines/index.astro
> +						利用開始した後に、UNTIL.・全代会情報処理推進特別委員会が不適当と認める内容となった場合、貸し出し対象に連絡を取った後適切な応答が無い場合、サブドメインの貸し出しを中止する。
「適切な応答」というのはTPOによって変化するので明確に定めたくないという気持ちはあります

2024-03-03 09:12 UTC, eniehack requested changes

2024-03-03 09:12 UTC, eniehack commented on src/pages/guidelines/index.astro
> +						利用開始した後に、UNTIL.または全代会情報処理推進特別委員会が不適当と認める内容となった場合、貸し出し対象に連絡を取った後適切な応答が無いとき、利用者の同意を確認せずにサブドメインの貸し出しを中止する場合があること。
```suggestion
						利用開始した後に、UNTIL.または全代会情報処理推進特別委員会が不適当と認める内容となった場合、貸し出し対象に連絡を取った後適切な応答が無いとき、利用者の意思に関わらず、サブドメインの貸し出しを中止する場合があること。
```

2024-03-03 09:13 UTC, oageo commented on src/pages/guidelines/index.astro
> +						利用開始した後に、UNTIL.または全代会情報処理推進特別委員会が不適当と認める内容となった場合、貸し出し対象に連絡を取った後適切な応答が無いとき、利用者の同意を確認せずにサブドメインの貸し出しを中止する場合があること。
日本語がきれいになったので良さそうです

2024-03-03 09:15 UTC, eniehack approved these changes

2024-03-03 09:16 UTC, merged